### ISSUE TITLE
Null Pointer Exception onFailedRequest for status code 429

### ISSUE THREAD

**Issue by Fiwel00** [meraki-analytics/orianna#120]
I am getting an issue while using Orianna with my application

This issue happens on version 4.0.0-rc6

Snippet from my maven pom.xml
> <dependency>
> 		<groupId>com.merakianalytics.orianna</groupId>
> 		<artifactId>orianna</artifactId>
> 		<version>4.0.0-rc6</version>
></dependency>

the issue in question is a null pointer exception that is being thrown after getting a rate limit exceeded error.
![image](https://user-images.githubusercontent.com/13918676/81005951-070bdd00-8e4f-11ea-8f99-c9463a924da7.png)

the code jumps to the onFailedRequest method and tries to retrieve the headers "Retry-After" and fails, filling up the retryAfterHeaders Collection with null

![image](https://user-images.githubusercontent.com/13918676/81005187-d5dedd00-8e4d-11ea-964a-8f91e8ff5655.png)

the null pointer exception arises few line below while trying to parse the retry value (marked in yellow)

Below is the stacktrace of the error:

java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at teamgg.ui.components.loadprofile.LoadProfileAL.actionPerformed(LoadProfileAL.java:15)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.NoSuchElementException
	at com.google.common.collect.Iterators$1.next(Iterators.java:81)
	at com.merakianalytics.orianna.datapipeline.riotapi.RiotAPIService$FailedRequestStrategy$RetryFromHeaders.onFailedRequest(RiotAPIService.java:348)
	at com.merakianalytics.orianna.datapipeline.riotapi.RiotAPIService.get(RiotAPIService.java:730)
	at com.merakianalytics.orianna.datapipeline.riotapi.RiotAPIService.get(RiotAPIService.java:667)
	at com.merakianalytics.orianna.datapipeline.riotapi.MatchAPI.getMatch(MatchAPI.java:294)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.merakianalytics.datapipelines.sources.AbstractDataSource.get(AbstractDataSource.java:49)
	at com.merakianalytics.datapipelines.sources.CompositeDataSource.get(CompositeDataSource.java:57)
	at com.merakianalytics.datapipelines.SourceHandler.get(SourceHandler.java:118)
	at com.merakianalytics.datapipelines.DataPipeline.get(DataPipeline.java:191)
	at com.merakianalytics.orianna.types.core.match.Match.loadCoreData(Match.java:748)
	at com.merakianalytics.orianna.types.core.GhostObject.load(GhostObject.java:414)
	at com.merakianalytics.orianna.types.core.match.Match.access$6600(Match.java:45)
	at com.merakianalytics.orianna.types.core.match.Match$1.get(Match.java:518)
	at com.merakianalytics.orianna.types.core.match.Match$1.get(Match.java:515)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.merakianalytics.orianna.types.core.match.Match.getBlueTeam(Match.java:622)
	at teamgg.ui.components.loadprofile.LoadProfileSW.getWinningteam(LoadProfileSW.java:268)
	at teamgg.ui.components.loadprofile.LoadProfileSW.loadMatchHistory(LoadProfileSW.java:74)
	at teamgg.ui.components.loadprofile.LoadProfileSW.doInBackground(LoadProfileSW.java:54)
	at teamgg.ui.components.loadprofile.LoadProfileSW.doInBackground(LoadProfileSW.java:1)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by robrua** [comment]
Oh wow, there should definitely be return statements in there - not sure how that's gone so long without coming up as an issue. Thanks for the detailed bug report! 

This should be fixed with c87f1dc. The change should be available in the latest SNAPSHOT build on sonatype.
