### ISSUE TITLE
Failed to deserialize

### ISSUE THREAD

**Issue by kireisnacks** [meraki-analytics/orianna#143]
Hey! So on 20 november i was working on a someone else's project with Orianna. Everything were working well all day then when the night came there is this error on every pc i have tried until today. If i remember it was also a patch day so i don't know if it involves but all i want to say is that i have tried all i could from my side even documenting Orianna's source code but unfortunately Gradle dependencies are read-only and i am scared of missing something important if i download the source code. So here i am asking for help if you could give this a quick scope. Also if you say that it's not from Orianna's side i will just pack my belongings and hide from shame. 

`ERROR [LogLevel$5]: Exception in thread "main" com.merakianalytics.orianna.types.common.OriannaException: Failed to deserialize object of type com.merakianalytics.orianna.types.dto.staticdata.ChampionList from JSON! Report this to the orianna team.
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.orianna.types.dto.DataObject.fromJSON(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.orianna.datapipeline.DataDragon.getChampionList(Unknown Source)
ERROR [LogLevel$5]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ERROR [LogLevel$5]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
ERROR [LogLevel$5]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
ERROR [LogLevel$5]:     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.datapipelines.sources.AbstractDataSource.get(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.datapipelines.SourceHandler.get(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.datapipelines.DataPipeline.get(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.orianna.types.core.staticdata.Champions.loadCoreData(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.orianna.types.core.GhostObject.load(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.merged.module@1.6.0/com.merakianalytics.orianna.types.core.GhostObject.load(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.overlay.main@1.5.1-SNAPSHOT/com.jcs.overlay.App.init(Unknown Source)
ERROR [LogLevel$5]:     at com.jcs.overlay.main@1.5.1-SNAPSHOT/com.jcs.overlay.App.main(Unknown Source)
ERROR [LogLevel$5]: Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4294967295) out of range of int (-2147483648 - 2147483647)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.merakianalytics.orianna.types.dto.staticdata.ChampionList["data"]->java.util.LinkedHashMap["Janna"]->com.merakianalytics.orianna.types.dto.staticdata.Champion["spells"]->java.util.ArrayList[1]->com.merakianalytics.orianna.types.dto.staticdata.ChampionSpell["range"]->java.util.ArrayList[0])
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.ObjectMapper._readValue(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.ObjectMapper.treeToValue(Unknown Source)
ERROR [LogLevel$5]:     ... 14 more
ERROR [LogLevel$5]: Caused by: com.fasterxml.jackson.core.exc.InputCoercionException: Numeric value (4294967295) out of range of int (-2147483648 - 2147483647)
 at [Source: UNKNOWN; line: -1, column: -1]
ERROR [LogLevel$5]:     at com.fasterxml.jackson.core@2.12.0/com.fasterxml.jackson.core.base.ParserMinimalBase._reportInputCoercion(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.core@2.12.0/com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.core@2.12.0/com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.core@2.12.0/com.fasterxml.jackson.core.base.ParserMinimalBase.reportOverflowInt(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.node.TreeTraversingParser.getIntValue(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     at com.fasterxml.jackson.databind@2.12.0/com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(Unknown Source)
ERROR [LogLevel$5]:     ... 36 more`

**Comment by ChroniclesOfTheRedeemed** [comment]
Got the same issue, says something is wrong with Janna? It could have something to do with Hwei being released and him having 10 abilities, nou sure.

**Comment by AzureAstral** [comment]
Any update about this ?
