### ISSUE TITLE
App crash on ARC Welder

### ISSUE THREAD

**Issue by gcmorrison** [meraki-analytics/orianna#19]
I've got a simple app that just loads the API and does a single call.  It works fine through an emulator and physical device, but it crashes when running it through the Google Chrome ARC Welder.  Stack trace below:
stack_trace: java.lang.RuntimeException
    at android.os.AsyncTask$5.done(AsyncTask.java:384)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$2.run(AsyncTask.java:280)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
Caused by com.robrua.orianna.type.exception.OriannaException
    at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:237)
    at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:165)
    at com.robrua.orianna.api.dto.StaticDataAPI.getChampions(StaticDataAPI.java:51)
    at com.robrua.orianna.api.dto.BaseRiotAPI.getChampions(BaseRiotAPI.java:277)
    at com.robrua.orianna.api.core.StaticDataAPI.getChampions(StaticDataAPI.java:86)
    at com.robrua.orianna.api.core.RiotAPI.getChampions(RiotAPI.java:81)
    at com.example.branch.MainActivity$1.doInBackground(MainActivity.java:39)
    at com.example.branch.MainActivity$1.doInBackground(MainActivity.java:35)
    at android.os.AsyncTask$4.call(AsyncTask.java:372)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ...4 more

**Comment by robrua** [comment]
Hey, are you running off of a release/snapshot version or a clone of the repo?

**Comment by gcmorrison** [comment]
Running off 2.2.7 auto pulled through maven

**Comment by robrua** [comment]
I updated the code to give a more useful stack trace where that exception was thrown. Can you try it w/the latest snapshot @ http://robrua.com/orianna/ and send me the full trace?

**Comment by gcmorrison** [comment]
Added the new code.  The rabbit hole goes deeper.

stack_trace: java.lang.RuntimeException
	at android.os.AsyncTask$5.done(AsyncTask.java:384)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$2.run(AsyncTask.java:280)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by com.robrua.orianna.type.exception.OriannaException
	at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:236)
	at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:164)
	at com.robrua.orianna.api.dto.StaticDataAPI.getChampions(StaticDataAPI.java:51)
	at com.robrua.orianna.api.dto.BaseRiotAPI.getChampions(BaseRiotAPI.java:276)
	at com.robrua.orianna.api.core.StaticDataAPI.getChampions(StaticDataAPI.java:86)
	at com.robrua.orianna.api.core.RiotAPI.getChampions(RiotAPI.java:80)
	at com.example.branch.MainActivity$1.doInBackground(MainActivity.java:39)
	at com.example.branch.MainActivity$1.doInBackground(MainActivity.java:35)
	at android.os.AsyncTask$4.call(AsyncTask.java:372)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	...4 more
Caused by java.net.SocketException
	at libcore.io.IoBridge.setSocketOption(IoBridge.java:306)
	at java.net.PlainSocketImpl.setOption(PlainSocketImpl.java:289)
	at java.net.Socket.setKeepAlive(Socket.java:453)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:373)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:225)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:204)
	...13 more
Caused by libcore.io.ErrnoException
	at libcore.io.Posix.setsockoptInt(Native Method)
	at libcore.io.ForwardingOs.setsockoptInt(ForwardingOs.java:122)
	at libcore.io.IoBridge.setSocketOptionErrno(IoBridge.java:338)
	at libcore.io.IoBridge.setSocketOption(IoBridge.java:304)
	...26 more

**Comment by robrua** [comment]
It looks like this is caused by a [known bug](https://code.google.com/p/chromium/issues/detail?id=384940) with ARC Welder right now.

**Comment by gcmorrison** [comment]
Well spotted!  Alright, thanks a lot for the effort :)
