### ISSUE TITLE
[Fatal]: com.robrua.orianna.type.exception.OriannaException: Request to Riot server failed! Report this to the Orianna team.

### ISSUE THREAD

**Issue by Fataler** [meraki-analytics/orianna#68]
Got this error when trying to use API. Is anything changed?

**Comment by Fataler** [comment]
`18:23:38] [Fatal] [JDA]: com.robrua.orianna.type.exception.OriannaException: Request to Riot server failed! Report this to the Orianna team.
	at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:261)
	at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:162)
	at com.robrua.orianna.api.dto.StaticDataAPI.getChampions(StaticDataAPI.java:49)
	at com.robrua.orianna.api.dto.BaseRiotAPI.getChampions(BaseRiotAPI.java:322)
	at com.robrua.orianna.api.core.StaticDataAPI.getChampions(StaticDataAPI.java:87)
	at com.robrua.orianna.api.core.RiotAPI.getChampions(RiotAPI.java:193)
	at MessageListenerExample.onMessageReceived(MessageListenerExample.java:315)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:327)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:129)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:51)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.dv8tion.jda.core.requests.WebSocketClient.handle(WebSocketClient.java:156)
	at net.dv8tion.jda.core.requests.WebSocketClient.ready(WebSocketClient.java:144)
	at net.dv8tion.jda.core.handle.ReadyHandler.guildLoadComplete(ReadyHandler.java:165)
	at net.dv8tion.jda.core.handle.ReadyHandler.guildSetupComplete(ReadyHandler.java:191)
	at net.dv8tion.jda.core.handle.GuildCreateHandler.lambda$handleInternally$97(GuildCreateHandler.java:45)
	at net.dv8tion.jda.core.entities.EntityBuilder.createGuildSecondPass(EntityBuilder.java:337)
	at net.dv8tion.jda.core.handle.GuildMembersChunkHandler.handleInternally(GuildMembersChunkHandler.java:59)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
Caused by: java.net.UnknownHostException: global.api.pvp.net
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.robrua.orianna.api.dto.BaseRiotAPI.get(BaseRiotAPI.java:202)
	... 30 more`

**Comment by Fataler** [comment]
https://pastebin.com/dh9jqQsY Here is a stack trace.

**Comment by robrua** [comment]
Hey,

The Riot API just removed the old v1/v2 endpoints, which orianna relied on. It therefore doesn't work right now. Support for the new v3 endpoints is under development on the v3-development branch, and should be done in the new few days. See #66.
