### ISSUE TITLE
java.lang.NumberFormatException: For input string: "lolpatch_7"

### ISSUE THREAD

**Issue by BillyD73** [meraki-analytics/orianna#89]
Hi guys, first of all thanks for this brilliant library! 

I've been trying to add serialization to my matches so I don't have to make huge quantities of calls with my limited API key. (While I'm here - my method was to essentially recreate the data classes with the values I needed and use the constructor to convert them from Orianna classes into my data-store classes, if there's an easier way e.g. using the sources for these classes and adding Serializable please let me know I'm fairly new to this!)

Anyway, upon trying to load one of my less recent matches (number 157) I get the following error:
`java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)
Caused by: java.lang.NumberFormatException: For input string: "lolpatch_7"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.merakianalytics.orianna.types.core.staticdata.Versions.truncate(Versions.java:101)
	at com.merakianalytics.orianna.types.core.match.Match$Team$1.get(Match.java:343)
	at com.merakianalytics.orianna.types.core.match.Match$Team$1.get(Match.java:337)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.merakianalytics.orianna.types.core.match.Match$Team.getBans(Match.java:371)
	at project.companion.data.Match.<init>(Match.java:39)
	at project.companion.data.MatchData.<init>(MatchData.java:28)
	at project.companion.Main.main(Main.java:147)
	... 11 more`

It looks like the truncate function in Versions on line 79 is getting a value "lolpatch_7" and trying to parseInt on that String, I've tried to breakpoint and look through the debug variables for any mention of "lolpatch_7" but haven't found anything. 

Any help or comments on this would be greatly appreciated!

Cheers
Billy

**Comment by robrua** [comment]
Hey,

It sounds like you're trying to serialize the data for caching purposes? Ori has built in caching that it will do automatically for you. There are currently implementations for MongoDB and Xodus (which will just store data on your local disk in files without the need for external DB software) [here](https://github.com/meraki-analytics/orianna-datastores). Additionally, Ori caches in-memory inside the Java process by default.

We try to avoid using the default Java serialization for storage (via Serializable) because it isn't very robust to class definition changes and future Java versions may choose to serialize differently. Additionally, there's been a few proposals lately to remove it entirely from the language.

Anyway, getting back on topic, if all you're looking for is caching the data - that's built in already. Let me know and I can give some examples on using the built in capabilities.

To address the lolpatch_7 issue - I thought I'd taken care of that in [this commit](https://github.com/meraki-analytics/orianna/commit/f78725825d6ee77c3a298db2a614d61c1b894450). Basically it's caused because orianna is trying to automatically match the static-data versions you see when you call something like match.getParticipants().get(0).getChampion() with the version the match is played on (so you're looking at data that was correct at the time of playing). Unfortunately, the patches reported by the match DTO are a lot more specific than the versions that the static-data endpoints take as parameters, so we have to try to resolve which static-data version the game was played on. We were doing it assuming all reported versions would be numerical, but it turns out really old games are on stuff like lolpatch_7. Upshot is that if you're using the latest SNAPSHOT version, this should hopefully already be fixed. It hasn't been in a release yet and will be in the next one.

Let me know if you're on the latest SNAPSHOT and still seeing this and I can look into it.

**Comment by BillyD73** [comment]
Silly me! The lolpatch issue is indeed remedied by the latest SNAPSHOT version and local caching works fine when the config is changed to use Xodus. Thanks Rob :)
